[package]
name = "mailviewer"
version = "0.9.92"
edition = "2021"

[dependencies]
webkit6 = "0.4.0"
gmime = "0.8.1"
gtk4 = "0.9.3"
open = "5.3.0"
nipper = "0.1.9"
log = "0.4.22"
env_logger = "0.11.5"
base64 = "0.22.1"
adw = { version = "0.7.1", features = ["v1_6"], package = "libadwaita" }
mktemp = "0.5.1"
ctor = "0.2.8"
msg_parser = "0.1.1"
uuid = "1.4.1"
lazy_static = "1.5.0"
hex = "0.4.3"
