imports_granularity = "Module"
imports_layout = "Horizontal"
indent_style = "Block"
max_width = 100
overflow_delimited_expr = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
struct_lit_single_line = false
tab_spaces = 2
unstable_features = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
normalize_comments = false
short_array_element_width_threshold = 3
single_line_let_else_max_width = 80
trailing_comma = "Vertical"