imports_granularity = "Module"
imports_layout = "Horizontal"
indent_style = "Block"
max_width = 100
overflow_delimited_expr = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
struct_lit_single_line = false
tab_spaces = 2
unstable_features = true
normalize_comments = true