unstable_features = true
indent_style = "Block"
reorder_imports = true
reorder_modules = true
tab_spaces = 2
overflow_delimited_expr = true
remove_nested_parens = true
imports_layout = "Horizontal"
imports_granularity = "Crate"
max_width = 240