name: prerelease

on:
  push:
    branches: [dev]
  pull_request:

jobs:
  flatpak:
    name: "build flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: mailviewer.flatpak
        manifest-path: io.github.alescdb.mailviewer.json
        cache-key: flatpak-builder-${{ github.sha }}
        upload-artifact: false
    - uses: actions/download-artifact@v4
    - name: show files
      run: find
    - uses: actions/upload-artifact@v4
      with:
        name: flatpak
        path: |
          LICENSE
          *.flatpak

  development:
    name: development
    needs: [flatpak]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: show files
      run: find
    - uses: "dciborow/action-github-releases@v1.0.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "dev"
        title: "Development Build"
        files: |
          **/LICENSE
          **/*.flatpak
