name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  flatpak:
    name: "build flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        dnf -y install pkg-config rust-pango-sys0.19+v1_52-devel.noarch nodejs
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: mailviewer.flatpak
        manifest-path: org.cosinus.mailviewer.json
        cache-key: flatpak-builder-${{ github.sha }}
        upload-artifact: false
    - uses: actions/upload-artifact@v4
      with:
        name: flatpak
        path: |
          LICENSE
          *.flatpak

  release:
    name: release
    needs: [flatpak]
    runs-on: ubuntu-latest
    steps:
    - uses: "dciborow/action-github-releases@v1.0.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/LICENSE
          **/*.flatpak
